Repository zeitgeistpm/zeitgeist, pull requests merged in 2021-08, with the labels that each got.

#231 Fourth iteration of the Court pallet
  Cargo.lock
  primitives/src/constants.rs
  primitives/src/traits/dispute_api.rs
  runtime/src/lib.rs
  zrml/court/Cargo.toml
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/court/src/tests.rs
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/simple-disputes/Cargo.toml
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/mock.rs
  zrml/simple-disputes/src/simple_disputes_pallet_api.rs
  zrml/simple-disputes/src/tests.rs
Labels: s:review-needed

#218 [Rikiddo] Implement Rikiddo trait and tests - part 1
  zrml/rikiddo/src/constants.rs
  zrml/rikiddo/src/tests.rs
  zrml/rikiddo/src/tests/ema_market_volume.rs
  zrml/rikiddo/src/tests/rikiddo_sigmoid_mv.rs
  zrml/rikiddo/src/tests/sigmoid_fee.rs
  zrml/rikiddo/src/traits.rs
  zrml/rikiddo/src/types.rs
  zrml/rikiddo/src/types/ema_market_volume.rs
  zrml/rikiddo/src/types/rikiddo_sigmoid_mv.rs
  zrml/rikiddo/src/types/sigmoid_fee.rs
Labels: s:review-needed

#233 Fifth iteration of the Court pallet
  .github/workflows/benchmark.yml
  .github/workflows/migration.yml
  .github/workflows/rust.yml
  Dockerfile
  node/src/service/service_parachain.rs
  primitives/src/constants.rs
  primitives/src/traits/dispute_api.rs
  primitives/src/traits/swaps.rs
  runtime/src/lib.rs
  rust-toolchain
  scripts/init.sh
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/court/src/tests.rs
  zrml/liquidity-mining/src/mock.rs
  zrml/liquidity-mining/src/track_incentives_based_on_bought_shares.rs
  zrml/liquidity-mining/src/utils.rs
  zrml/market-commons/src/lib.rs
  zrml/orderbook-v1/src/mock.rs
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/rikiddo/Cargo.toml
  zrml/rikiddo/src/mock.rs
  zrml/rikiddo/src/types/ema_market_volume.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/simple_disputes_pallet_api.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/mock.rs
  zrml/swaps/src/utils.rs
Labels: s:accepted

#234 Battery station deployment
  .github/workflows/chachacha.yml
  .github/workflows/rococo.yml
  node/res/bs_parachain.json
  node/src/chain_spec/battery_park.rs
  node/src/chain_spec/battery_station.rs
  node/src/chain_spec/dev.rs
  scripts/build-parachain-spec.sh
  scripts/parachain/battery-station-relay.sh
  scripts/parachain/chachacha.sh
  scripts/parachain/local.sh
  scripts/parachain/rococo.sh
  scripts/parachain/testing-network-commons.sh
  scripts/parachain/testing-network.sh
Labels: s:in-progress

#247 [Orderbook-v1] Implement fuzz targets
  Cargo.lock
  Cargo.toml
  scripts/tests/fuzz.sh
  zrml/orderbook-v1/Cargo.toml
  zrml/orderbook-v1/fuzz/Cargo.toml
  zrml/orderbook-v1/fuzz/orderbook_v1_full_workflow.rs
  zrml/orderbook-v1/src/lib.rs
  zrml/orderbook-v1/src/mock.rs
Labels: s:review-needed

#244 Sixth iteration of the Court pallet
  primitives/src/lib.rs
  primitives/src/resolution_counters.rs
  primitives/src/traits/dispute_api.rs
  primitives/src/types.rs
  runtime/src/lib.rs
  zrml/court/src/lib.rs
  zrml/court/src/tests.rs
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/simple_disputes_pallet_api.rs
  zrml/swaps/src/lib.rs
Labels: s:review-needed

#270 [PM] Single extrinsic for creating and deploying a pool
  primitives/src/traits/swaps.rs
  runtime/src/lib.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
  zrml/swaps/src/lib.rs
Labels: s:accepted

#259 Improvements
  Cargo.lock
  node/src/chain_spec/mod.rs
  node/src/cli/cli_parachain.rs
  primitives/src/constants.rs
  primitives/src/market.rs
  primitives/src/traits/dispute_api.rs
  runtime/src/lib.rs
  zrml/court/Cargo.toml
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/court/src/tests.rs
  zrml/liquidity-mining/Cargo.toml
  zrml/liquidity-mining/src/lib.rs
  zrml/liquidity-mining/src/liquidity_mining_pallet_api.rs
  zrml/liquidity-mining/src/mock.rs
  zrml/liquidity-mining/src/owned_values_params.rs
  zrml/liquidity-mining/src/tests.rs
  zrml/liquidity-mining/src/track_incentives_based_on_bought_shares.rs
  zrml/liquidity-mining/src/track_incentives_based_on_sold_shares.rs
  zrml/liquidity-mining/src/utils.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/market_commons_pallet_api.rs
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/rikiddo/src/mock.rs
  zrml/simple-disputes/src/lib.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/src/mock.rs
  zrml/swaps/src/tests.rs
Labels: s:review-needed
