Repository zeitgeistpm/zeitgeist, pull requests merged in 2022-11, with the labels that each got.

#846 Filter dangerous calls
  runtime/zeitgeist/src/lib.rs
Labels: s:accepted

#866 Update MarketIdsPer*Block benchmarks
  zrml/prediction-markets/src/benchmarks.rs
Labels: s:accepted

#778 Use Origin in authorized pallet to resolve dispute for market with Authorized MarketDisputeMechanism.
  docs/changelog_for_devs.md
  primitives/src/market.rs
  runtime/common/src/lib.rs
  zrml/authorized/src/benchmarks.rs
  zrml/authorized/src/lib.rs
  zrml/authorized/src/mock.rs
  zrml/authorized/src/tests.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/migrations.rs
  zrml/market-commons/src/tests.rs
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/tests.rs
Labels: s:accepted, i:spec-changed :warning:

#863 Slash oracle bound while resolving disputed market, if oracle does not report or reports wrong outcome
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
Labels: s:accepted

#682 Implement Global Disputes
  Cargo.lock
  Cargo.toml
  README.md
  docs/changelog_for_devs.md
  primitives/Cargo.toml
  primitives/src/constants.rs
  primitives/src/constants/mock.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  scripts/benchmarks/configuration.sh
  scripts/benchmarks/quick_check.sh
  scripts/benchmarks/run_benchmarks.sh
  scripts/tests/misc.sh
  zrml/global-disputes/Cargo.toml
  zrml/global-disputes/README.md
  zrml/global-disputes/src/benchmarks.rs
  zrml/global-disputes/src/global_disputes_pallet_api.rs
  zrml/global-disputes/src/lib.rs
  zrml/global-disputes/src/mock.rs
  zrml/global-disputes/src/tests.rs
  zrml/global-disputes/src/types.rs
  zrml/global-disputes/src/weights.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/README.md
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/prediction-markets/src/weights.rs
  zrml/simple-disputes/src/lib.rs
Labels: s:accepted, i:spec-changed :warning:, i:transactions-changed :warning:

#765 Add missing license files
  node/src/cli.rs
Labels: s:accepted

#833 Implement automatic on-chain arbitrage
  docs/changelog_for_devs.md
  runtime/common/src/lib.rs
  zrml/authorized/src/mock.rs
  zrml/court/src/mock.rs
  zrml/global-disputes/src/mock.rs
  zrml/liquidity-mining/src/mock.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/market_commons_pallet_api.rs
  zrml/market-commons/src/mock.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/simple-disputes/src/mock.rs
  zrml/swaps/src/arbitrage.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/mock.rs
  zrml/swaps/src/root.rs
  zrml/swaps/src/tests.rs
  zrml/swaps/src/utils.rs
  zrml/swaps/src/weights.rs
Labels: s:accepted, i:spec-changed :warning:

#879 Fix max disputes to avoid migration
  runtime/battery-station/src/parameters.rs
Labels: s:accepted

#878 Add with_fees boolean parameter for Swaps getSpotPrices()
  docs/changelog_for_devs.md
  runtime/common/src/lib.rs
  zrml/swaps/rpc/src/lib.rs
  zrml/swaps/runtime-api/src/lib.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/mock.rs
  zrml/swaps/src/tests.rs
  zrml/swaps/src/utils.rs
Labels: s:accepted

#850 Upgrade to polkadot-v0.9.26
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec/battery_station.rs
  node/src/chain_spec/dev.rs
  node/src/chain_spec/mod.rs
  node/src/chain_spec/zeitgeist.rs
  node/src/cli.rs
  node/src/cli/cli_parachain.rs
  node/src/command.rs
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/court/src/lib.rs
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/liquidity-mining/src/track_incentives_based_on_bought_shares.rs
  zrml/liquidity-mining/src/track_incentives_based_on_sold_shares.rs
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/orderbook-v1/fuzz/Cargo.toml
  zrml/orderbook-v1/src/mock.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/fuzz/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/prediction-markets/src/mock.rs
  zrml/rikiddo/Cargo.toml
  zrml/rikiddo/fuzz/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/fuzz/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
  zrml/swaps/src/mock.rs
Labels: s:accepted

#661 Configure and test whitelisted XCM reserve transfers
  Cargo.lock
  docs/changelog_for_devs.md
  misc/types.json
  node/Cargo.toml
  node/src/chain_spec/battery_station.rs
  node/src/chain_spec/dev.rs
  node/src/chain_spec/mod.rs
  primitives/src/asset.rs
  primitives/src/constants.rs
  primitives/src/types.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/integration_tests/mod.rs
  runtime/battery-station/src/integration_tests/xcm/mod.rs
  runtime/battery-station/src/integration_tests/xcm/setup.rs
  runtime/battery-station/src/integration_tests/xcm/test_net.rs
  runtime/battery-station/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/battery-station/src/integration_tests/xcm/tests/mod.rs
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/lib.rs
  runtime/battery-station/src/parachain_params.rs
  runtime/battery-station/src/parameters.rs
  runtime/battery-station/src/xcm_config.rs
  runtime/battery-station/src/xcm_config/asset_registry.rs
  runtime/battery-station/src/xcm_config/config.rs
  runtime/battery-station/src/xcm_config/fees.rs
  runtime/battery-station/src/xcm_config/mod.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/integration_tests/mod.rs
  runtime/zeitgeist/src/integration_tests/xcm/mod.rs
  runtime/zeitgeist/src/integration_tests/xcm/setup.rs
  runtime/zeitgeist/src/integration_tests/xcm/test_net.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/mod.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/lib.rs
  runtime/zeitgeist/src/parachain_params.rs
  runtime/zeitgeist/src/parameters.rs
  runtime/zeitgeist/src/xcm_config.rs
  runtime/zeitgeist/src/xcm_config/asset_registry.rs
  runtime/zeitgeist/src/xcm_config/config.rs
  runtime/zeitgeist/src/xcm_config/fees.rs
  runtime/zeitgeist/src/xcm_config/mod.rs
  zrml/swaps/src/lib.rs
Labels: s:accepted, i:spec-changed :warning:

#886 Update weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  scripts/benchmarks/configuration.sh
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:accepted

#867 Update version to 0.3.7
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#890 Reduce vote ratio for advisory disputes
  runtime/common/src/lib.rs
Labels: s:accepted
