Repository zeitgeistpm/zeitgeist, pull requests merged in 2022-08, with the labels that each got.

#711 Let markets open their pools when they start
  runtime/src/lib.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/tests.rs
Labels: s:accepted

#733 Add minimum balance to CPMM logic
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/tests.rs
  zrml/swaps/src/utils.rs
Labels: s:accepted, i:spec-changed :warning:

#729 Cleanup MarketIdsPerReportBlock and MarketIdsPerDisputeBlock in resolution_manager()
  runtime/src/lib.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
Labels: s:accepted

#720 Add info regarding updating `RuntimeVersion`
  CONTRIBUTING.md
Labels: p:low, s:in-progress

#750 Optimize default build by excluding fuzz tests
  Cargo.toml
Labels: s:accepted

#748 Bump versions to v0.3.5
  Cargo.lock
  docs/changelog_for_devs.md
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#744 Allow market approval by single `AdvisoryCommittee` member
  docs/diagrams/png/market_state_diagram.png
  docs/diagrams/src/market_state_diagram.puml
  docs/diagrams/svg/market_state_diagram.svg
  runtime/common/src/lib.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
Labels: s:accepted, i:spec-changed :warning:

#749 Apply updated configuration to Zeitgeist runtime
  Cargo.lock
  node/src/command_helper.rs
  primitives/Cargo.toml
  primitives/src/constants.rs
  primitives/src/constants/mock.rs
  primitives/src/pool.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/authorized/Cargo.toml
  zrml/authorized/src/mock.rs
  zrml/court/Cargo.toml
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/court/src/tests.rs
  zrml/liquidity-mining/Cargo.toml
  zrml/liquidity-mining/src/mock.rs
  zrml/market-commons/Cargo.toml
  zrml/market-commons/src/mock.rs
  zrml/orderbook-v1/Cargo.toml
  zrml/orderbook-v1/src/mock.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/fuzz/Cargo.toml
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/rikiddo/Cargo.toml
  zrml/rikiddo/src/mock.rs
  zrml/simple-disputes/Cargo.toml
  zrml/simple-disputes/src/mock.rs
  zrml/styx/Cargo.toml
  zrml/styx/src/mock.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/fuzz/Cargo.toml
  zrml/swaps/fuzz/utils.rs
  zrml/swaps/src/mock.rs
Labels: s:accepted

#753 Update weights
  node/src/command.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  runtime/common/src/weights/parachain_staking.rs
  runtime/zeitgeist/src/parameters.rs
  scripts/benchmarks/configuration.sh
  scripts/benchmarks/run_benchmarks.sh
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:accepted

#758 Remove old migrations
  runtime/common/src/lib.rs
  zrml/court/src/migrations.rs
  zrml/prediction-markets/src/migrations.rs
Labels: s:accepted

#768 Remove `report_todo` option
  rustfmt.toml
Labels: p:low, s:review-needed

#767 Toml auto format script and github workflow update.
  .github/workflows/rust.yml
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  rustfmt.toml
  scripts/tests/format.sh
  scripts/tests/misc.sh
  taplo.toml
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/orderbook-v1/fuzz/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/fuzz/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#763 Clarify error docstring
  zrml/swaps/src/lib.rs
Labels: s:accepted

#770 Update rust toolchain
  rust-toolchain
Labels: s:accepted

#775 Use `which` instead of `whereis` in format.sh script.
  rust-toolchain
  scripts/tests/format.sh
Labels: s:accepted
