Repository zeitgeistpm/zeitgeist, pull requests merged in 2022-12, with the labels that each got.

#897 Remove old migrations and ReportPeriod and DisputePeriod from prediction markets Config
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/market-commons/src/migrations.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
Labels: s:accepted

#901 Use working tracing crate
  Cargo.lock
  node/Cargo.toml
Labels: s:accepted

#900 Tightly coupled market-commons with prediction markets.
  primitives/src/traits.rs
  primitives/src/traits/market_commons_pallet_api.rs
  runtime/common/src/lib.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/tests.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
Labels: p:high, s:accepted

#913 Add Chaintroopers audit report
  audit/Chaintroopers Audit Report of Zeitgeist PM (2022).pdf
Labels: p:low, s:accepted

#874 Remove `report_todo` from `rustfmt` config
  rustfmt.toml
Labels: p:low, s:accepted

#902 [GlobalDisputes] Prevent benchmark failure
  Cargo.lock
  zrml/global-disputes/Cargo.toml
  zrml/global-disputes/src/benchmarks.rs
Labels: s:accepted
