Repository zeitgeistpm/zeitgeist, pull requests merged in 2023-10, with the labels that each got.

#1109 Update weight templates to reflect weights-v2
  misc/frame_weight_template.hbs
  misc/orml_weight_template.hbs
  misc/weight_template.hbs
Labels: s:accepted

#1099 Implement partial fills for orderbook pallet
  Cargo.lock
  primitives/src/constants.rs
  primitives/src/constants/mock.rs
  primitives/src/pool.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/parameters.rs
  zrml/orderbook-v1/Cargo.toml
  zrml/orderbook-v1/fuzz/orderbook_v1_full_workflow.rs
  zrml/orderbook-v1/src/benchmarks.rs
  zrml/orderbook-v1/src/lib.rs
  zrml/orderbook-v1/src/mock.rs
  zrml/orderbook-v1/src/tests.rs
  zrml/orderbook-v1/src/types.rs
  zrml/orderbook-v1/src/utils.rs
  zrml/orderbook-v1/src/weights.rs
  zrml/prediction-markets/src/lib.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/utils.rs
Labels: s:accepted

#1103 Merge release-v0.4.0 branch into main
  Cargo.lock
  node/Cargo.toml
  node/res/bs_parachain.json
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/authorized/src/weights.rs
  zrml/court/Cargo.toml
  zrml/court/src/weights.rs
  zrml/global-disputes/Cargo.toml
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/Cargo.toml
  zrml/liquidity-mining/src/weights.rs
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/weights.rs
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/styx/src/weights.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
  zrml/swaps/src/lib.rs
  zrml/swaps/src/weights.rs
Labels: s:review-needed

#1142 Update version
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/neo-swaps/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:review-needed

#1143 Update weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/neo-swaps/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:review-needed

#1137 Restructure to unambiguous BalanceOf<T>
  primitives/src/traits/market_commons_pallet_api.rs
  runtime/common/src/lib.rs
  zrml/authorized/src/lib.rs
  zrml/authorized/src/mock.rs
  zrml/court/src/benchmarks.rs
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/global-disputes/src/lib.rs
  zrml/global-disputes/src/mock.rs
  zrml/global-disputes/src/utils.rs
  zrml/liquidity-mining/src/lib.rs
  zrml/liquidity-mining/src/mock.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/mock.rs
  zrml/neo-swaps/src/mock.rs
  zrml/orderbook-v1/src/lib.rs
  zrml/orderbook-v1/src/mock.rs
  zrml/orderbook-v1/src/utils.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/simple-disputes/src/benchmarks.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/mock.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/mock.rs
Labels: s:accepted

#1147 Include system remarks to help testing process
  runtime/battery-station/src/lib.rs
Labels: s:review-needed

#1145 Remove `admin_destroy_market`
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
  zrml/prediction-markets/src/weights.rs
Labels: s:review-needed, i:transactions-changed :warning:

#1148 Add disputant to market dispute event
  docs/changelog_for_devs.md
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
Labels: p:high, s:review-needed

#1144 Allow selling complete sets regardless of market status
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
Labels: s:review-needed

#1153 Merge branch release-v0.4.1
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/authorized/src/weights.rs
  zrml/court/Cargo.toml
  zrml/court/src/weights.rs
  zrml/global-disputes/Cargo.toml
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/Cargo.toml
  zrml/liquidity-mining/src/weights.rs
  zrml/market-commons/Cargo.toml
  zrml/neo-swaps/Cargo.toml
  zrml/neo-swaps/src/weights.rs
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/prediction-markets/src/weights.rs
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/styx/src/weights.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
  zrml/swaps/src/weights.rs
Labels: s:review-needed

#1151 Improve durability of fixed point conversion function
  primitives/src/math/fixed.rs
Labels: s:review-needed

#1155 Prepend market_id to MarketCreatorFee* events
  zrml/swaps/src/lib.rs
  zrml/swaps/src/tests.rs
Labels: s:review-needed

#1156 Fix market creator paying fees to himself
  zrml/swaps/src/lib.rs
Labels: s:review-needed

#1157 Fix build
  primitives/src/math/fixed.rs
  zrml/swaps/src/lib.rs
Labels: s:review-needed

#1165 Emit court opened event
  zrml/court/src/lib.rs
Labels: s:accepted

#1127 Implement close markets early feature
  docs/changelog_for_devs.md
  primitives/src/constants/mock.rs
  primitives/src/market.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/authorized/src/lib.rs
  zrml/court/src/benchmarks.rs
  zrml/court/src/tests.rs
  zrml/global-disputes/src/utils.rs
  zrml/liquidity-mining/src/tests.rs
  zrml/market-commons/src/tests.rs
  zrml/neo-swaps/src/benchmarking.rs
  zrml/neo-swaps/src/mock.rs
  zrml/orderbook-v1/src/utils.rs
  zrml/parimutuel/src/utils.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/prediction-markets/src/weights.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/tests.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/mock.rs
Labels: s:accepted, i:spec-changed :warning:, i:transactions-changed :warning:

#1163 Update neo-swaps events
  zrml/neo-swaps/src/lib.rs
  zrml/neo-swaps/src/tests/deploy_pool.rs
  zrml/neo-swaps/src/tests/exit.rs
Labels: s:review-needed

#1170 Extend benchmark list
  Cargo.lock
  Cargo.toml
  README.md
  runtime/battery-station/Cargo.toml
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  scripts/benchmarks/configuration.sh
  scripts/tests/fuzz.sh
  zrml/orderbook/Cargo.toml
  zrml/orderbook/README.md
  zrml/orderbook/fuzz/Cargo.toml
  zrml/orderbook/fuzz/orderbook_v1_full_workflow.rs
  zrml/orderbook/src/benchmarks.rs
  zrml/orderbook/src/lib.rs
  zrml/orderbook/src/mock.rs
  zrml/orderbook/src/tests.rs
  zrml/orderbook/src/types.rs
  zrml/orderbook/src/utils.rs
  zrml/orderbook/src/weights.rs
Labels: s:review-needed

#1168 Update versions
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/neo-swaps/Cargo.toml
  zrml/orderbook/Cargo.toml
  zrml/parimutuel/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:review-needed

#1169 Add updated weights from reference machine
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/neo-swaps/src/weights.rs
  zrml/orderbook/src/weights.rs
  zrml/parimutuel/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:review-needed
