Repository zeitgeistpm/zeitgeist, pull requests merged in 2023-09, with the labels that each got.

#1057 Implement market creator incentives
  Cargo.lock
  docs/changelog_for_devs.md
  primitives/Cargo.toml
  primitives/src/constants/mock.rs
  primitives/src/market.rs
  primitives/src/traits/swaps.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/authorized/src/lib.rs
  zrml/court/src/benchmarks.rs
  zrml/court/src/tests.rs
  zrml/global-disputes/src/utils.rs
  zrml/liquidity-mining/src/tests.rs
  zrml/market-commons/src/tests.rs
  zrml/prediction-markets/fuzz/Cargo.toml
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/tests.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/fuzz/create_pool.rs
  zrml/swaps/fuzz/utils.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/mock.rs
  zrml/swaps/src/tests.rs
  zrml/swaps/src/utils.rs
Labels: s:review-needed

#1098 Update versions to v0.4.0
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:review-needed

#1101 Update weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:accepted

#1119 Add bad block of the proof size fiasko to Battery Station chain spec
  node/res/bs_parachain.json
Labels: s:accepted, s:review-needed

#1120 Adapt arbitrage weight calculations to proof sizes
  zrml/swaps/src/lib.rs
Labels: s:accepted

#1126 Fix taplo build
  .github/workflows/rust.yml
  scripts/tests/format.sh
Labels: s:accepted

#1104 Add constant attribute to MaxCreatorFee
  zrml/prediction-markets/src/lib.rs
Labels: s:accepted

#1100 Implement trusted markets
  primitives/src/market.rs
  runtime/battery-station/src/lib.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/src/lib.rs
  zrml/authorized/src/tests.rs
  zrml/court/src/benchmarks.rs
  zrml/court/src/lib.rs
  zrml/court/src/tests.rs
  zrml/global-disputes/src/migrations.rs
  zrml/global-disputes/src/utils.rs
  zrml/liquidity-mining/src/tests.rs
  zrml/market-commons/src/tests.rs
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/tests.rs
  zrml/prediction-markets/src/weights.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/tests.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/mock.rs
Labels: s:review-needed

#1090 Add Substrate style guide
  CONTRIBUTING.md
  docs/STYLE_GUIDE.md
Labels: s:accepted

#1130 Fix imports
  zrml/authorized/src/lib.rs
Labels: s:accepted
