Repository zeitgeistpm/zeitgeist, pull requests merged in 2023-01, with the labels that each got.

#892 Track reserved (non-dispute) bonds
  docs/changelog_for_devs.md
  primitives/src/constants/mock.rs
  primitives/src/market.rs
  primitives/src/traits/dispute_api.rs
  primitives/src/traits/market_commons_pallet_api.rs
  runtime/common/src/lib.rs
  zrml/authorized/src/lib.rs
  zrml/court/src/lib.rs
  zrml/court/src/tests.rs
  zrml/liquidity-mining/src/tests.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/tests.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/tests.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/tests.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/tests.rs
Labels: s:accepted, i:spec-changed :warning:

#914 Add missing call filters
  runtime/battery-station/src/lib.rs
  runtime/zeitgeist/src/lib.rs
Labels: s:accepted

#871 Run benchmark tests in separate environments
  zrml/authorized/src/benchmarks.rs
  zrml/court/src/benchmarks.rs
  zrml/global-disputes/src/benchmarks.rs
  zrml/liquidity-mining/src/benchmarks.rs
  zrml/orderbook-v1/src/benchmarks.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/styx/src/benchmarks.rs
  zrml/swaps/src/benchmarks.rs
Labels: s:accepted

#872 Make dispute benchmarks more precise
  zrml/authorized/src/lib.rs
  zrml/prediction-markets/src/benchmarks.rs
Labels: s:accepted

#862 Allow MDMs to control future resolutions
  docs/changelog_for_devs.md
  primitives/src/constants/mock.rs
  primitives/src/market.rs
  primitives/src/traits.rs
  primitives/src/traits/dispute_api.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/authorized/src/benchmarks.rs
  zrml/authorized/src/lib.rs
  zrml/authorized/src/migrations.rs
  zrml/authorized/src/mock.rs
  zrml/authorized/src/mock_storage.rs
  zrml/authorized/src/tests.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/prediction-markets/src/weights.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/mock.rs
Labels: p:high, s:accepted, i:spec-changed :warning:, i:transactions-changed :warning:, i:config-values :computer:

#877 Unreserve dispute bonds when destroying a market
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
Labels: s:review-needed, i:spec-changed :warning:

#932 Update crate and runtime version
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#908 Add maximum lifetime for markets
  primitives/src/constants.rs
  primitives/src/constants/mock.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
Labels: s:accepted, i:spec-changed :warning:, i:config-values :computer:

#941 Fix: typos
  README.md
Labels: s:accepted

#894 Add base_asset to Market structure and make prediction_markets pallet use it instead of Asset::Ztg
  .github/workflows/rust.yml
  Cargo.lock
  docs/changelog_for_devs.md
  primitives/src/market.rs
  primitives/src/traits/dispute_api.rs
  primitives/src/traits/market_commons_pallet_api.rs
  primitives/src/types.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/integration_tests/xcm/setup.rs
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/lib.rs
  runtime/battery-station/src/xcm_config/asset_registry.rs
  runtime/battery-station/src/xcm_config/fees.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/integration_tests/xcm/setup.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/lib.rs
  runtime/zeitgeist/src/xcm_config/asset_registry.rs
  runtime/zeitgeist/src/xcm_config/fees.rs
  scripts/tests/aux-functions.sh
  scripts/tests/misc.sh
  zrml/authorized/src/lib.rs
  zrml/authorized/src/mock.rs
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/court/src/tests.rs
  zrml/liquidity-mining/src/tests.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/migrations.rs
  zrml/market-commons/src/tests.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/orml_asset_registry.rs
  zrml/prediction-markets/src/tests.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/mock.rs
  zrml/simple-disputes/src/tests.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/tests.rs
Labels: p:high, s:accepted, i:transactions-changed :warning:

#930 Respect all asset's existential deposit
  Cargo.lock
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/parameters.rs
Labels: s:accepted

#953 Update weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: p:high, s:accepted

#951 Use tag when publishing a parachain docker image
  .github/workflows/docker-hub-parachain.yml
Labels: s:accepted

#950 Add CodeCov and Discord badges
  README.md
Labels: s:accepted

#937 Fix order of arguments in `get_spot_price`
  zrml/swaps/rpc/src/lib.rs
Labels: s:accepted

#931 Basic tag.yml script
  .github/workflows/rust.yml
  .github/workflows/tag.yml
Labels: s:accepted

#952 Use crystal ball logo in logs
  node/src/service/service_parachain.rs
Labels: s:accepted

#958 Remove crowdloan_rewards pallet
  Cargo.lock
  node/src/chain_spec/additional_chain_spec.rs
  node/src/chain_spec/battery_station.rs
  node/src/chain_spec/dev.rs
  node/src/chain_spec/mod.rs
  node/src/chain_spec/zeitgeist.rs
  primitives/src/constants/ztg.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/battery-station/src/parachain_params.rs
  runtime/common/src/lib.rs
  runtime/common/src/weights/mod.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  runtime/zeitgeist/src/parachain_params.rs
  scripts/benchmarks/configuration.sh
Labels: s:accepted

#943 [PM] Set market end when admin closes the market
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
Labels: s:accepted

#903 [PM] Reserve `OutsiderBond` for report, when the oracle fails to report
  Cargo.lock
  primitives/src/constants/mock.rs
  primitives/src/market.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/court/src/tests.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/tests.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/simple-disputes/src/tests.rs
Labels: s:accepted, i:config-values :computer:
