Repository zeitgeistpm/zeitgeist, pull requests merged in 2023-08, with the labels that each got.

#1056 Foreign tx fee improvements
  runtime/common/src/fees.rs
Labels: s:accepted

#1058 Use u32 asset id for foreign tx fee payment
  primitives/src/types.rs
  runtime/common/src/fees.rs
  runtime/common/src/lib.rs
Labels: s:accepted

#1061 Fix workflow runs on main
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
Labels: s:accepted

#1060 Maintain dependencies in workspace
  Cargo.toml
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/orderbook-v1/fuzz/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/fuzz/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/rikiddo/fuzz/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/fuzz/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#557 Add Hadolint and Trivy Checks
  .github/workflows/docker-hub-parachain.yml
  .github/workflows/docker-hub.yml
  .hadolint.yml
  Dockerfile
Labels: s:accepted

#1041 Enable certain dispatchable calls in smart contracts
  runtime/battery-station/src/lib.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/lib.rs
Labels: s:accepted

#1063 Update versions
  Cargo.lock
  docs/changelog_for_devs.md
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#1065 Fix try-runtime makefile targets
  Makefile
Labels: s:review-needed

#1066 Fix parachain-staking benchmarks
  Cargo.lock
  Cargo.toml
  node/src/chain_spec/dev.rs
Labels: s:review-needed

#1070 Fix fee tests
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
Labels: s:accepted

#1068 Update weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:accepted

#1071 Merge release-v0.3.11 into main
  Cargo.lock
  Cargo.toml
  Makefile
  docs/changelog_for_devs.md
  node/Cargo.toml
  node/src/chain_spec/dev.rs
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/authorized/src/weights.rs
  zrml/court/Cargo.toml
  zrml/court/src/weights.rs
  zrml/global-disputes/Cargo.toml
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/Cargo.toml
  zrml/liquidity-mining/src/weights.rs
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/prediction-markets/src/weights.rs
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/styx/src/weights.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
  zrml/swaps/src/weights.rs
Labels: s:accepted

#1074 Run checks when the "s:accepted" label is set
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
Labels: s:accepted

#1045 Fix mergify config status check names
  .mergify.yml
Labels: s:accepted

#1076 Samuel fix client update
  .github/workflows/client-auto-update.yml
  .github/workflows/docker-hub-parachain.yml
  scripts/ansible/client-auto-update-playbook.yml
Labels: s:accepted

#1078 Adjust maximum market lifetime
  primitives/src/constants.rs
Labels: s:accepted

#912 [Global Disputes] Fix issues after first battery station live test
  Cargo.lock
  docs/changelog_for_devs.md
  primitives/src/constants/mock.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  zrml/court/src/lib.rs
  zrml/global-disputes/README.md
  zrml/global-disputes/src/benchmarks.rs
  zrml/global-disputes/src/global_disputes_pallet_api.rs
  zrml/global-disputes/src/lib.rs
  zrml/global-disputes/src/migrations.rs
  zrml/global-disputes/src/mock.rs
  zrml/global-disputes/src/tests.rs
  zrml/global-disputes/src/types.rs
  zrml/global-disputes/src/utils.rs
  zrml/global-disputes/src/weights.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
Labels: s:accepted, i:needs-audit, i:spec-changed :warning:, i:transactions-changed :warning:, i:config-values :computer:

#1079 Update dependencies to v0.9.38
  Cargo.lock
  Cargo.toml
  HEADER_GPL3
  misc/frame_weight_template.hbs
  misc/orml_weight_template.hbs
  misc/weight_template.hbs
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  node/src/service/service_parachain.rs
  node/src/service/service_standalone.rs
  runtime/battery-station/src/integration_tests/xcm/setup.rs
  runtime/battery-station/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/lib.rs
  runtime/battery-station/src/parachain_params.rs
  runtime/battery-station/src/parameters.rs
  runtime/battery-station/src/xcm_config/config.rs
  runtime/common/src/fees.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/integration_tests/xcm/setup.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/lib.rs
  runtime/zeitgeist/src/parachain_params.rs
  runtime/zeitgeist/src/parameters.rs
  runtime/zeitgeist/src/xcm_config/config.rs
  rust-toolchain
  scripts/benchmarks/configuration.sh
  scripts/benchmarks/quick_check.sh
  scripts/benchmarks/run_benchmarks.sh
  zrml/authorized/src/benchmarks.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/src/benchmarks.rs
  zrml/rikiddo/src/tests/rikiddo_sigmoid_mv/price.rs
  zrml/styx/src/benchmarks.rs
  zrml/swaps/src/arbitrage.rs
Labels: s:accepted
