Repository zeitgeistpm/zeitgeist, pull requests merged in 2023-07, with the labels that each got.

#895 Add review checklist
  docs/review_checklist.md
Labels: p:low, s:accepted

#910 Add verbose feature in script/tests/fuzz.sh
  .github/workflows/rust.yml
  scripts/tests/fuzz.sh
Labels: s:accepted

#1033 Release v0.3.9
  Cargo.lock
  Cargo.toml
  Dockerfile
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  scripts/init.sh
  zrml/authorized/Cargo.toml
  zrml/authorized/src/weights.rs
  zrml/court/Cargo.toml
  zrml/court/src/weights.rs
  zrml/global-disputes/Cargo.toml
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/Cargo.toml
  zrml/liquidity-mining/src/weights.rs
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/orderbook-v1/src/weights.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/prediction-markets/src/weights.rs
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/styx/src/weights.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
  zrml/swaps/src/weights.rs
Labels: s:review-needed

#1035 Don't panic on spec_version mismatch during try-runtime
  Makefile
Labels: s:review-needed

#1034 Remove old migrations
  runtime/common/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
Labels: s:accepted

#971 RPC for querying prices for all assets of given pool_id.
  Cargo.lock
  node/src/chain_spec/battery_station.rs
  node/src/chain_spec/dev.rs
  runtime/battery-station/src/lib.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/lib.rs
  zrml/swaps/rpc/src/lib.rs
  zrml/swaps/runtime-api/Cargo.toml
  zrml/swaps/runtime-api/src/lib.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/mock.rs
  zrml/swaps/src/tests.rs
Labels: s:accepted

#777 Add simple mergify config. It uses branch protection rules from github configuration.
  .mergify.yml
Labels: s:accepted

#1038 Add prediction market and swaps proxies
  primitives/src/proxy_type.rs
  runtime/common/src/lib.rs
Labels: s:accepted

#1037 Integrate --relay-chain-rpc-url flag
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service/service_parachain.rs
  node/src/service/service_standalone.rs
Labels: s:accepted

#1036 Add dispatch call indices
  zrml/authorized/src/lib.rs
  zrml/court/src/lib.rs
  zrml/global-disputes/src/lib.rs
  zrml/liquidity-mining/src/lib.rs
  zrml/orderbook-v1/src/lib.rs
  zrml/prediction-markets/src/lib.rs
  zrml/styx/src/lib.rs
  zrml/swaps/src/lib.rs
Labels: s:accepted

#1043 Run workflows required for merges when label s:review-needed is set
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
Labels: s:accepted

#1042 Adjust mergify status checks and label management
  .mergify.yml
Labels: s:accepted

#1022 Implement foreign asset transaction fees
  Cargo.lock
  docs/changelog_for_devs.md
  node/Cargo.toml
  node/src/benchmarking.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/fees.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
Labels: s:accepted

#944 Zeitgeist Client Update Automation
  .github/workflows/client-auto-update.yml
  .github/workflows/docker-hub-parachain.yml
  scripts/ansible/client-auto-update-playbook.yml
Labels: s:accepted

#1044 Don't notify codeowners when only weight files or Cargo.toml are changed
  CODEOWNERS
Labels: s:accepted

#1047 Update versions
  Cargo.lock
  docs/changelog_for_devs.md
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/orderbook-v1/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#1048 Update weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:accepted

#1050 Run try-runtime also on RC tags
  .github/workflows/try-runtime.yml
Labels: s:accepted

#1052 Client auto update
  .github/workflows/client-auto-update.yml
Labels: s:accepted

#1053 Add get_fee_factor_test
  runtime/common/src/fees.rs
Labels: s:accepted
