Repository zeitgeistpm/zeitgeist, pull requests merged in 2023-06, with the labels that each got.

#1009 Fix pipeline
  .github/workflows/benchmark.yml
  .github/workflows/migration.yml
  .github/workflows/rust.yml
  .github/workflows/tag.yml
  Dockerfile
  scripts/init.sh
Labels: s:review-needed

#1013 Update toolchain
  Cargo.lock
  node/Cargo.toml
  primitives/src/constants.rs
  primitives/src/traits/zeitgeist_multi_reservable_currency.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/integration_tests/xcm/setup.rs
  runtime/battery-station/src/integration_tests/xcm/test_net.rs
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/parachain_params.rs
  runtime/battery-station/src/parameters.rs
  runtime/battery-station/src/xcm_config/fees.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/integration_tests/xcm/setup.rs
  runtime/zeitgeist/src/integration_tests/xcm/test_net.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/parachain_params.rs
  runtime/zeitgeist/src/parameters.rs
  runtime/zeitgeist/src/xcm_config/fees.rs
  rust-toolchain
  zrml/authorized/src/benchmarks.rs
  zrml/authorized/src/lib.rs
  zrml/authorized/src/mock_storage.rs
  zrml/court/src/benchmarks.rs
  zrml/court/src/lib.rs
  zrml/global-disputes/src/benchmarks.rs
  zrml/global-disputes/src/lib.rs
  zrml/global-disputes/src/tests.rs
  zrml/liquidity-mining/src/benchmarks.rs
  zrml/liquidity-mining/src/lib.rs
  zrml/orderbook-v1/src/benchmarks.rs
  zrml/orderbook-v1/src/lib.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/rikiddo/fuzz/balance_to_fixedu_conversion.rs
  zrml/rikiddo/fuzz/ema_market_volume_estimate_ema.rs
  zrml/rikiddo/fuzz/ema_market_volume_first_state.rs
  zrml/rikiddo/fuzz/ema_market_volume_second_state.rs
  zrml/rikiddo/fuzz/ema_market_volume_third_state.rs
  zrml/rikiddo/fuzz/fee_sigmoid.rs
  zrml/rikiddo/fuzz/fixedi_to_fixedu_conversion.rs
  zrml/rikiddo/fuzz/fixedu_to_balance_conversion.rs
  zrml/rikiddo/fuzz/fixedu_to_fixedi_conversion.rs
  zrml/rikiddo/fuzz/rikiddo_pallet.rs
  zrml/rikiddo/fuzz/rikiddo_with_calculated_fee.rs
  zrml/rikiddo/fuzz/rikiddo_with_initial_fee.rs
  zrml/rikiddo/src/lib.rs
  zrml/rikiddo/src/mock.rs
  zrml/rikiddo/src/types.rs
  zrml/rikiddo/src/types/sigmoid_fee.rs
  zrml/simple-disputes/src/lib.rs
  zrml/styx/src/benchmarks.rs
  zrml/styx/src/tests.rs
  zrml/swaps/fuzz/utils.rs
  zrml/swaps/src/benchmarks.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/mock.rs
Labels: s:review-needed

#1006 Test all features in test scripts
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
  scripts/tests/all-sequencial.sh
  scripts/tests/aux-functions.sh
  scripts/tests/coverage.sh
  scripts/tests/misc.sh
  scripts/tests/parachain.sh
  scripts/tests/standalone.sh
  scripts/tests/test.sh
Labels: s:accepted

#1011 Use reasonable storage fee
  docs/changelog_for_devs.md
  primitives/src/constants.rs
  runtime/battery-station/src/parameters.rs
  runtime/zeitgeist/src/parameters.rs
Labels: s:accepted

#1014 Make `MaxMarketLifetime` a constant
  zrml/prediction-markets/src/lib.rs
Labels: s:accepted

#1016 Fix docs of `MarketEdited`
  zrml/prediction-markets/src/lib.rs
Labels: s:accepted

#1021 Add style guide
  docs/STYLE_GUIDE.md
Labels: s:review-needed

#1017 Add code owners
  CODEOWNERS
Labels: s:accepted

#1018 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s:accepted

#1012 Include pallet-contracts into the runtime
  Cargo.lock
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  scripts/benchmarks/configuration.sh
Labels: s:accepted, i:spec-changed :warning:, i:transactions-changed :warning:

#963 Add automatic copyright notice verification
  .github/workflows/rust.yml
  .gitignore
  scripts/check-license/Makefile
  scripts/check-license/requirements.txt
  scripts/check-license/resources/test_read
  scripts/check-license/resources/test_read_fails_on_broken_copyright_notice
  scripts/check-license/setup.py
  scripts/check-license/src/check_license/__init__.py
  scripts/check-license/src/check_license/check_license.py
  scripts/check-license/src/check_license/console.py
  scripts/check-license/src/check_license/copyright.py
  scripts/check-license/src/check_license/errors.py
  scripts/check-license/tests/test_check_license.py
  scripts/check-license/tests/test_copyright.py
  scripts/update-copyright.sh
Labels: s:accepted

#1027 Update weight templates copyright
  misc/frame_weight_template.hbs
  misc/orml_weight_template.hbs
  misc/weight_template.hbs
Labels: s:accepted

#1028 Use argument in init.sh to avoid usage of sudo
  Dockerfile
  scripts/init.sh
Labels: s:review-needed

#1029 Fix name collision
  runtime/zeitgeist/src/lib.rs
Labels: s:accepted

#1030 Use updated Rococo bootnodes
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
Labels: s:accepted
