Repository zeitgeistpm/zeitgeist, pull requests merged in 2024-01, with the labels that each got.

#1225 Improve XCM fee handling
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/xcm_config/config.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/xcm_config/config.rs
Labels: s:accepted

#1226 Remove court and global disputes from call filter for the main-net
  runtime/zeitgeist/src/lib.rs
Labels: s:accepted

#1211 Merge release v0.4.3
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/neo-swaps/Cargo.toml
  zrml/orderbook/Cargo.toml
  zrml/parimutuel/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#1160 Reduce `market_status_manager` aka `on_initialize` iterations
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/tests.rs
  zrml/prediction-markets/src/weights.rs
Labels: s:accepted, i:spec-changed :warning:, i:transactions-changed :warning:

#1227 Update versions
  Cargo.lock
  macros/Cargo.toml
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/court/Cargo.toml
  zrml/global-disputes/Cargo.toml
  zrml/liquidity-mining/Cargo.toml
  zrml/market-commons/Cargo.toml
  zrml/neo-swaps/Cargo.toml
  zrml/orderbook/Cargo.toml
  zrml/parimutuel/Cargo.toml
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/rikiddo/Cargo.toml
  zrml/simple-disputes/Cargo.toml
  zrml/styx/Cargo.toml
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
Labels: s:accepted

#1228 Update style guide to streamline reviews
  docs/STYLE_GUIDE.md
  docs/review_checklist.md
Labels: s:accepted

#1233 Reduce benchmark runs of Zeitgeist pallets
  scripts/benchmarks/configuration.sh
Labels: s:accepted

#1234 Set inflation to more than zero for a full benchmark of handle_inflation
  zrml/court/src/benchmarks.rs
Labels: s:accepted

#1232 Update weights
  HEADER_GPL3
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_contracts.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  zrml/authorized/src/weights.rs
  zrml/court/src/weights.rs
  zrml/global-disputes/src/weights.rs
  zrml/liquidity-mining/src/weights.rs
  zrml/neo-swaps/src/weights.rs
  zrml/orderbook/src/weights.rs
  zrml/parimutuel/src/weights.rs
  zrml/prediction-markets/src/weights.rs
  zrml/styx/src/weights.rs
  zrml/swaps/src/weights.rs
Labels: s:accepted

#1235 Implement `force_pool_exit` and disable other zrml-swaps functions
  runtime/battery-station/src/lib.rs
  runtime/zeitgeist/src/lib.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/tests.rs
Labels: s:accepted

#1223 Implement and test `bmul_bdiv_*`; use in zrml-orderbook and zrml-parimutuel
  primitives/src/math/fixed.rs
  zrml/orderbook/src/lib.rs
  zrml/parimutuel/src/lib.rs
Labels: s:accepted

#1243 Utilize Merigify's Merge Queue
  .mergify.yml
Labels: s:accepted

#1244 Set in-progress when need and rerun CI in merge queue
  .mergify.yml
Labels: s:review-needed

#1245 Avoid mergify dequeue
  .mergify.yml
Labels: s:review-needed

#1238 Extend neo-swaps tests and clean up `math.rs`
  Cargo.lock
  Cargo.toml
  zrml/neo-swaps/src/consts.rs
  zrml/neo-swaps/src/math.rs
Labels: s:accepted

#1241 Remove migrations and dead code
  primitives/src/market.rs
  runtime/common/src/lib.rs
  zrml/market-commons/src/migrations.rs
  zrml/neo-swaps/src/migration.rs
  zrml/neo-swaps/src/types/mod.rs
  zrml/neo-swaps/src/types/solo_lp.rs
  zrml/orderbook/src/migrations.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/migrations.rs
  zrml/swaps/src/lib.rs
  zrml/swaps/src/migrations.rs
Labels: s:accepted

#1242 Reorganize prediction-market tests
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/prediction-markets/src/tests/admin_move_market_to_closed.rs
  zrml/prediction-markets/src/tests/admin_move_market_to_resolved.rs
  zrml/prediction-markets/src/tests/approve_market.rs
  zrml/prediction-markets/src/tests/buy_complete_set.rs
  zrml/prediction-markets/src/tests/close_trusted_market.rs
  zrml/prediction-markets/src/tests/create_market.rs
  zrml/prediction-markets/src/tests/create_market_and_deploy_pool.rs
  zrml/prediction-markets/src/tests/dispute.rs
  zrml/prediction-markets/src/tests/dispute_early_close.rs
  zrml/prediction-markets/src/tests/edit_market.rs
  zrml/prediction-markets/src/tests/integration.rs
  zrml/prediction-markets/src/tests/manually_close_market.rs
  zrml/prediction-markets/src/tests/mod.rs
  zrml/prediction-markets/src/tests/on_initialize.rs
  zrml/prediction-markets/src/tests/on_market_close.rs
  zrml/prediction-markets/src/tests/on_resolution.rs
  zrml/prediction-markets/src/tests/redeem_shares.rs
  zrml/prediction-markets/src/tests/reject_early_close.rs
  zrml/prediction-markets/src/tests/reject_market.rs
  zrml/prediction-markets/src/tests/report.rs
  zrml/prediction-markets/src/tests/request_edit.rs
  zrml/prediction-markets/src/tests/schedule_early_close.rs
  zrml/prediction-markets/src/tests/sell_complete_set.rs
  zrml/prediction-markets/src/tests/start_global_dispute.rs
Labels: s:accepted

#1189 New Asset System - Implement asset-router
  CODEOWNERS
  Cargo.lock
  Cargo.toml
  README.md
  primitives/src/assets/campaign_assets.rs
  primitives/src/assets/currencies.rs
  primitives/src/assets/custom_assets.rs
  primitives/src/constants/mock.rs
  primitives/src/types.rs
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/integration_tests/xcm/setup.rs
  runtime/battery-station/src/integration_tests/xcm/test_net.rs
  runtime/battery-station/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/parameters.rs
  runtime/battery-station/src/xcm_config/asset_registry.rs
  runtime/battery-station/src/xcm_config/config.rs
  runtime/battery-station/src/xcm_config/fees.rs
  runtime/common/src/fees.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/integration_tests/xcm/setup.rs
  runtime/zeitgeist/src/integration_tests/xcm/test_net.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/parameters.rs
  runtime/zeitgeist/src/xcm_config/asset_registry.rs
  runtime/zeitgeist/src/xcm_config/config.rs
  runtime/zeitgeist/src/xcm_config/fees.rs
  zrml/asset-router/Cargo.toml
  zrml/asset-router/README.md
  zrml/asset-router/src/lib.rs
  zrml/asset-router/src/mock.rs
  zrml/asset-router/src/tests/create.rs
  zrml/asset-router/src/tests/destroy.rs
  zrml/asset-router/src/tests/inspect.rs
  zrml/asset-router/src/tests/mod.rs
  zrml/asset-router/src/tests/multi_currency.rs
  zrml/asset-router/src/tests/multi_lockable_currency.rs
  zrml/asset-router/src/tests/multi_reservable_currency.rs
  zrml/asset-router/src/tests/named_multi_reservable_currency.rs
  zrml/neo-swaps/src/mock.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/src/lib.rs
  zrml/swaps/src/tests.rs
Labels: s:review-needed

#1246 Improve fee payment management
  zrml/prediction-markets/src/lib.rs
Labels: s:accepted

#1247 Fix Rust and Discord badge
  README.md
Labels: s:accepted
