Repository zeitgeistpm/zeitgeist, pull requests merged in 2024-03, with the labels that each got.

#1286 Update Codeowners
  CODEOWNERS
Labels: s:accepted

#1282 New Asset System - Integrate into Prediction Markets and Parimutuel
  Cargo.lock
  Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/lib.rs
  zrml/market-commons/src/lib.rs
  zrml/market-commons/src/tests.rs
  zrml/parimutuel/Cargo.toml
  zrml/parimutuel/src/benchmarking.rs
  zrml/parimutuel/src/lib.rs
  zrml/parimutuel/src/mock.rs
  zrml/parimutuel/src/tests/assets.rs
  zrml/parimutuel/src/tests/buy.rs
  zrml/parimutuel/src/tests/claim.rs
  zrml/parimutuel/src/tests/mod.rs
  zrml/parimutuel/src/tests/refund.rs
  zrml/parimutuel/src/utils.rs
  zrml/parimutuel/src/weights.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/fuzz/pm_full_workflow.rs
  zrml/prediction-markets/src/benchmarks.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
  zrml/prediction-markets/src/tests/admin_move_market_to_closed.rs
  zrml/prediction-markets/src/tests/admin_move_market_to_resolved.rs
  zrml/prediction-markets/src/tests/approve_market.rs
  zrml/prediction-markets/src/tests/buy_complete_set.rs
  zrml/prediction-markets/src/tests/close_market.rs
  zrml/prediction-markets/src/tests/create_market.rs
  zrml/prediction-markets/src/tests/create_market_and_deploy_pool.rs
  zrml/prediction-markets/src/tests/dispute.rs
  zrml/prediction-markets/src/tests/dispute_early_close.rs
  zrml/prediction-markets/src/tests/edit_market.rs
  zrml/prediction-markets/src/tests/integration.rs
  zrml/prediction-markets/src/tests/manually_close_market.rs
  zrml/prediction-markets/src/tests/mod.rs
  zrml/prediction-markets/src/tests/on_initialize.rs
  zrml/prediction-markets/src/tests/on_market_close.rs
  zrml/prediction-markets/src/tests/on_resolution.rs
  zrml/prediction-markets/src/tests/redeem_shares.rs
  zrml/prediction-markets/src/tests/reject_early_close.rs
  zrml/prediction-markets/src/tests/reject_market.rs
  zrml/prediction-markets/src/tests/report.rs
  zrml/prediction-markets/src/tests/request_edit.rs
  zrml/prediction-markets/src/tests/schedule_early_close.rs
  zrml/prediction-markets/src/tests/sell_complete_set.rs
  zrml/prediction-markets/src/tests/start_global_dispute.rs
Labels: s:accepted

#1284 New Asset System - Integrate into remaining pallets
  Cargo.lock
  zrml/authorized/src/lib.rs
  zrml/authorized/src/mock.rs
  zrml/liquidity-mining/src/tests.rs
  zrml/neo-swaps/Cargo.toml
  zrml/neo-swaps/src/benchmarking.rs
  zrml/neo-swaps/src/lib.rs
  zrml/neo-swaps/src/macros.rs
  zrml/neo-swaps/src/mock.rs
  zrml/neo-swaps/src/tests/deploy_pool.rs
  zrml/neo-swaps/src/tests/join.rs
  zrml/neo-swaps/src/tests/mod.rs
  zrml/neo-swaps/src/tests/sell.rs
  zrml/simple-disputes/src/lib.rs
  zrml/simple-disputes/src/mock.rs
  zrml/simple-disputes/src/tests.rs
  zrml/swaps/src/lib.rs
Labels: s:accepted

#1283 New Asset System - Integrate into Orderbook/Court/GlobalDisputes
  Cargo.toml
  zrml/court/src/benchmarks.rs
  zrml/court/src/lib.rs
  zrml/court/src/mock.rs
  zrml/court/src/tests.rs
  zrml/global-disputes/src/mock.rs
  zrml/global-disputes/src/utils.rs
  zrml/orderbook/Cargo.toml
  zrml/orderbook/src/benchmarks.rs
  zrml/orderbook/src/lib.rs
  zrml/orderbook/src/mock.rs
  zrml/orderbook/src/tests.rs
  zrml/orderbook/src/utils.rs
Labels: s:accepted

#1287 New Asset System - Integrate into XCM
  primitives/src/types.rs
  runtime/battery-station/src/integration_tests/xcm/setup.rs
  runtime/battery-station/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/battery-station/src/integration_tests/xcm/tests/transfers.rs
  runtime/battery-station/src/parameters.rs
  runtime/battery-station/src/xcm_config/asset_registry.rs
  runtime/battery-station/src/xcm_config/config.rs
  runtime/battery-station/src/xcm_config/fees.rs
  runtime/common/src/fees.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/integration_tests/xcm/setup.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/currency_id_convert.rs
  runtime/zeitgeist/src/integration_tests/xcm/tests/transfers.rs
  runtime/zeitgeist/src/parameters.rs
  runtime/zeitgeist/src/xcm_config/asset_registry.rs
  runtime/zeitgeist/src/xcm_config/config.rs
  runtime/zeitgeist/src/xcm_config/fees.rs
  zrml/neo-swaps/src/mock.rs
  zrml/neo-swaps/src/tests/join.rs
  zrml/orderbook/src/lib.rs
  zrml/prediction-markets/src/lib.rs
  zrml/prediction-markets/src/mock.rs
Labels: s:review-needed

#1285 Add previous stake information after rejoin
  Cargo.lock
  macros/src/lib.rs
  runtime/common/src/lib.rs
  zrml/court/Cargo.toml
  zrml/court/src/benchmarks.rs
  zrml/court/src/lib.rs
  zrml/court/src/migrations.rs
  zrml/court/src/tests.rs
  zrml/court/src/types.rs
Labels: s:accepted

#1291 Fix Hybrid Router clippy and tests
  Cargo.lock
  primitives/src/constants.rs
  primitives/src/constants/mock.rs
  runtime/battery-station/src/parameters.rs
  runtime/common/src/lib.rs
  runtime/zeitgeist/src/parameters.rs
  scripts/benchmarks/configuration.sh
  zrml/hybrid-router/Cargo.toml
  zrml/hybrid-router/src/benchmarking.rs
  zrml/hybrid-router/src/lib.rs
  zrml/hybrid-router/src/mock.rs
  zrml/hybrid-router/src/tests/buy.rs
  zrml/hybrid-router/src/tests/mod.rs
  zrml/hybrid-router/src/tests/sell.rs
  zrml/hybrid-router/src/utils.rs
  zrml/hybrid-router/src/weights.rs
Labels: s:in-progress
