Repository zeitgeistpm/zeitgeist, pull requests merged in 2025-02, with the labels that each got.

#1404 Use three out of five membership threshold
  runtime/common/src/lib.rs
Labels: s:accepted

#1391 Add docs
  README.md
  primitives/src/traits/combinatorial_tokens_api.rs
  primitives/src/traits/combinatorial_tokens_benchmark_helper.rs
  primitives/src/traits/combinatorial_tokens_unsafe_api.rs
  zrml/combinatorial-tokens/README.md
  zrml/combinatorial-tokens/src/lib.rs
  zrml/combinatorial-tokens/src/traits/combinatorial_id_manager.rs
  zrml/futarchy/README.md
  zrml/futarchy/src/lib.rs
  zrml/futarchy/src/types/proposal.rs
  zrml/neo-swaps/src/lib.rs
  zrml/neo-swaps/src/types/decision_market_oracle.rs
Labels: s:in-progress

#1407 Revert "Use `MultiLocation` for tx fee payment instead of `u32`"
  primitives/src/types.rs
  runtime/common/src/fees.rs
Labels: s:accepted

#1392 Add fuzz tests for combinatorial tokens, pool and futarchy
  Cargo.lock
  Cargo.toml
  primitives/src/traits/market_commons_pallet_api.rs
  scripts/tests/fuzz.sh
  zrml/combinatorial-tokens/fuzz/Cargo.toml
  zrml/combinatorial-tokens/fuzz/common.rs
  zrml/combinatorial-tokens/fuzz/merge_position.rs
  zrml/combinatorial-tokens/fuzz/redeem_position.rs
  zrml/combinatorial-tokens/fuzz/split_position.rs
  zrml/combinatorial-tokens/src/lib.rs
  zrml/combinatorial-tokens/src/mock/mod.rs
  zrml/combinatorial-tokens/src/mock/types/mod.rs
  zrml/futarchy/Cargo.toml
  zrml/futarchy/fuzz/Cargo.toml
  zrml/futarchy/fuzz/submit_proposal.rs
  zrml/futarchy/src/mock/mod.rs
  zrml/futarchy/src/mock/types/oracle.rs
  zrml/futarchy/src/types/proposal.rs
  zrml/neo-swaps/fuzz/Cargo.toml
  zrml/neo-swaps/fuzz/combo_buy.rs
  zrml/neo-swaps/fuzz/combo_sell.rs
  zrml/neo-swaps/fuzz/common.rs
  zrml/neo-swaps/fuzz/deploy_combinatorial_pool.rs
  zrml/neo-swaps/src/lib.rs
Labels: s:accepted

#1398 Merge release-v0.5.6 into main
  Cargo.lock
  integration-tests/package.json
  integration-tests/pnpm-lock.yaml
  integration-tests/tests/common-tests.ts
  integration-tests/tests/rt-upgrade-battery-station-chopsticks/test-battery-station-chopsticks-runtime-upgrade.ts
  integration-tests/tests/rt-upgrade-zeitgeist-chopsticks/test-zeitgeist-chopsticks-runtime-upgrade.ts
  macros/Cargo.toml
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/battery-station/Cargo.toml
  runtime/battery-station/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/frame_system.rs
  runtime/common/src/weights/orml_currencies.rs
  runtime/common/src/weights/orml_tokens.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_bounties.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_membership.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_vesting.rs
  runtime/zeitgeist/Cargo.toml
  runtime/zeitgeist/src/lib.rs
  zrml/authorized/Cargo.toml
  zrml/authorized/src/weights.rs
  zrml/court/Cargo.toml
  zrml/court/src/weights.rs
  zrml/global-disputes/Cargo.toml
  zrml/global-disputes/src/weights.rs
  zrml/hybrid-router/Cargo.toml
  zrml/hybrid-router/src/weights.rs
  zrml/market-commons/Cargo.toml
  zrml/neo-swaps/Cargo.toml
  zrml/neo-swaps/src/weights.rs
  zrml/orderbook/Cargo.toml
  zrml/orderbook/src/weights.rs
  zrml/parimutuel/Cargo.toml
  zrml/parimutuel/src/weights.rs
  zrml/prediction-markets/Cargo.toml
  zrml/prediction-markets/runtime-api/Cargo.toml
  zrml/prediction-markets/src/weights.rs
  zrml/styx/Cargo.toml
  zrml/styx/src/weights.rs
  zrml/swaps/Cargo.toml
  zrml/swaps/rpc/Cargo.toml
  zrml/swaps/runtime-api/Cargo.toml
  zrml/swaps/src/weights.rs
Labels: s:accepted

#1405 Remove migrations and add changelog for devs
  docs/changelog_for_devs.md
  runtime/common/src/lib.rs
Labels: s:accepted

#1408 Use `MultiLocation` for tx fee payment instead of `u32`
  primitives/src/types.rs
  runtime/common/src/fees.rs
Labels: s:accepted

#1409 Use three out of five membership threshold
  runtime/common/src/lib.rs
Labels: s:accepted

#1411 Update changelog for devs
  Cargo.lock
  docs/changelog_for_devs.md
Labels: s:review-needed

#1415 Fix github workflows
  .github/workflows/integration-tests.yml
  scripts/tests/format.sh
Labels: s:accepted

#1414 Increase max market lifetime
  primitives/src/constants.rs
Labels: s:review-needed

#1416 Update integration tests
  integration-tests/configs/zeitgeist.yml
  integration-tests/scripts/download-polkadot.sh
Labels: s:accepted
